### PR TITLE
init. website design

### PR DESCRIPTION
**Pull request by catlover819**
this is my pull request for the website's design.

+ added image folder in main folder
  + added 3 images in image folder (for index.html)
+ added index.css in main folder (for index.html's design)
+ modified index.html to have a design

### CODE REVIEW

**Review by jadenkiu — APPROVED** [review]
A few linking issues to fix.

**Comment by nurikimchi** [comment]
Good starting point. Plan to make these important changes:

- [ ] Broken images
- [ ] Fonts are default Times New Roman
- [ ] "Contributors" section text too big, no left margin too
- [ ] Include placeholder on some note for the big empty gray box for tutorial

Screenshot 2023-10-23 at 10 17 23 PM

Screenshot 2023-10-23 at 10 17 30 PM

Screenshot 2023-10-23 at 10 17 37 PM


Screenshot 2023-10-23 at 10 17 45 PM

**Comment by nurikimchi** [comment]
Just commit these changes on this branch and we'll review again before pushing.

**Comment by jadenkiu** [comment]
@prathamrn is suggesting we use the cities' existing website instead, check communications server for latest progress and decisions @nurikimchi

**Comment by nurikimchi** [comment]
Closed in favor of pull request #7.

**Pull request closed without merging**
