### PR TITLE
tutorial gif hover play

### PR DESCRIPTION
**Pull request by catlover819**
added <div> hover functionality in index.css so that the thumbnails of each gif (static .png images) would turn into gifs when hovered over.
turned old styling in index.css into comments (prior to this pull)
re-added index.css as a stylesheet for index.html.
added 3 .png files into /images to act as static thumbnails for tutorial gifs.
changed the tutorialClick, tutorialPortal, and tutorialTurn  elements into <div> elements for compatibility with the hover function.

### CODE REVIEW

**Review by nurikimchi — DISMISSED** [review]
All GIFs are broken. I'm using Chrome. This could be an issue with our original code itself or #7 method of just copying over their website code. I don't see a .gif file being imported into index.html so for now resolve the issue first that's in our original code by committing again.
Screenshot 2023-10-28 at 8 23 50 PM

Screenshot 2023-10-28 at 8 19 57 PM

**Review by jadenkiu — APPROVED** [review]
I fixed the sourcing, everything else looks good

**Comment by nurikimchi** [comment]
Ran project on my end, works on Chrome and Safari. Lgtm!

**Review by nurikimchi — APPROVED** [review]
Ran project on my end, works on Safari and Chrome. Nice work guys! Especially with GIFs continuing from where they left off.

**Pull request merged**
